name: testing1
on:

  push:
    branches: [main]
    
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    
  jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        -uses: actions/checkout@markdown-parser
        
        - name: helloworld
        run: echo Hello, world!
        
        -name: actually testing
        run: | 
        echo javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar MarkdownParseTest.java 
        
        run: |
        echo java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore MarkdownParseTest
          
        
      
